### PR TITLE
Fix for #2568

### LINKED ISSUE #2568: Command for preparing route cache file
Hello guys. I didn't find command for preparing cache file for routes. I have to create custom script which will generate route file before publishing my project to production.
This feature will be very useful, I think.

### PR DESCRIPTION
**Pull request by l0gicgate**
This is a fix for the logic for detecting if user provided router cache file is valid or not.

The following cases are valid:
- If the directory is not writable, but the file already exists and is writable
- If the directory is writable and the file specified does not exist

For the record, if you specify a file that doesn't exist, FastRoute will create it and populate it with the appropriate cache data.

This effectively closes #2568 

The PR for the docs is here [#334](https://github.com/slimphp/Slim-Website/pull/334)

### CODE REVIEW

File: Slim/Router.php [hunk 1]
```diff
@@ -130,20 +130,38 @@ public function getBasePath()
...
         return $this;
     }
 
+    /**
+     * This method is in place to facilitate unit tests
+     * @param $cacheFile
+     *
+     * @return bool
+     */
+    protected function isCacheFileWritable($cacheFile)
```
Comment (l0gicgate) [inline Slim/Router.php]: @akrabat as you can see I had to add this method because I cannot redefine the global function `is_writable()`.

Originally, I tried creating the directory/files required and setting the permissions correctly to hit those test cases but it was not working on the CI or my local windows build, only on local unix builds.

This way at least I can stub this method and make it return what I need to hit those test cases. Let me know if you have a better solution.

File: Slim/Router.php [hunk 2]
```diff
@@ -130,20 +130,51 @@ public function getBasePath()
...
     }
 
+    /**
+     * This method is in place to facilitate unit tests
+     *
+     * @param $cacheFile
+     *
+     * @return bool
+     */
+    protected function isCacheFileReadable($cacheFile)
```
Comment (l0gicgate) [inline Slim/Router.php]: @akrabat as you can see I had to add these methods `Router::isCacheFileReadable()` and `Router::isCacheDirWritable()` because I cannot redefine the global functions `is_writable()` or `is_readable()`. Which made unit testing almost impossible.

Originally, I tried creating the directory/files required and setting the permissions correctly to hit those test cases but it was not working on the CI or my local windows build, only on local unix builds.

This way at least I can stub this method and make it return what I need to hit those test cases. Let me know if you have a better solution.

File: Slim/Router.php [hunk 3]
```diff
@@ -130,20 +130,51 @@ public function getBasePath()
      */
     public function setCacheFile($cacheFile)
     {
+        $this->cacheFile = $cacheFile;
```
Comment (akrabat) [inline Slim/Router.php]: Don't set `$cacheFile` to the class property before we've validated it.

File: Slim/Router.php (hunk 2 above)
Comment (akrabat) [reply Slim/Router.php]: Technically, as this class is in a namespace, you could mock out `is_readable()`/`is_readable()`. See `tests/Assets/HeaderFunctions.php` - I wrote it up [here](https://akrabat.com/replacing-a-built-in-php-function-when-testing-a-component/).

File: Slim/Router.php (hunk 3 above)
Comment (l0gicgate) [reply Slim/Router.php]: why? if it's invalid, an exception is thrown anyway so it doesn't matter that it is set.

Comment (akrabat) [reply Slim/Router.php]: The user could catch the exception and then continue.

File: tests/Assets/HeaderFunctions.php [hunk 4]
```diff
@@ -57,3 +57,31 @@ function header($string, $replace = true, $statusCode = null)
         ]
     );
 }
+
```
Comment (akrabat) [inline tests/Assets/HeaderFunctions.php:60]: We should rename this file now that it containers functions other than header functions. Maybe `PhpFunctions.php`?

**Review by akrabat — APPROVED** [review]
