### PR TITLE
Fix using CallableResolvable as group middleware

### LINKED ISSUE #1377: Slim3 middleware on route groups doesn't work
The problem exists when adding middleware to route groups. Example below:

```
class Test {
    public function run($request, $response, $next){
        $response->write('+');
        $response = $next($request, $response);
        $response->write('-');
        return $response;
    }
}
```
#### Fails

```
$app = new \Slim\App();
$app->group('/admin', function () use ($app) {
    $app->get('/test', function($request, $response, $args) {
        return $response->write('works!');
    });
})->add('Test:run');
$app->run();
```
#### Works

But if you add same middleware to single route everything works fine.

```
$app = new \Slim\App();
$app->group('/admin', function () use ($app) {
    $app->get('/test', function($request, $response, $args) {
        return $response->write('works!');
    })->add('Test:run');
});
$app->run();
```

### PR DESCRIPTION
**Pull request by opengeek**
The container was not available for resolving a CallableResolvable when invoking a RouteGroup

Should resolve #1377

### CODE REVIEW

File: Slim/App.php [hunk 1]
```diff
@@ -263,7 +263,7 @@ public function map(array $methods, $pattern, $callable)
      */
     public function group($pattern, $callable)
     {
-        $group = $this->container->get('router')->pushGroup($pattern, $callable);
+        $group = $this->container->get('router')->pushGroup($this->container, $pattern, $callable);
```
Comment (silentworks) [inline Slim/App.php]: Just add `$group->setContainer($this->container);` after `$group = $this->container->get('router')->pushGroup($pattern, $callable);` and that should fix the issue. Sorry only realised this after you made all these changes.
