### PR TITLE
4.x - Add route context helper

### LINKED ISSUE #2758: Accessing RouteParser From Route Callables
We need to figure out a sane way for users to access the `RouteParser` component from a route callable. Right now you have to jump through hoops to get access to it from within a route and it feels unnatural to have to map it via DI.

Perhaps an internal middleware, or perhaps creating a route callable wrapper which would provide the component.

Open to suggestions.

### LINKED ISSUE #2761: Routing tests have impossible case
`RoutingMiddlewareTest::testRouteIsNotStoredOnMethodNotAllowed()` expects an exception, but it also includes inspection of the request. The [inspection part of the test][1] is never reached, because `RoutingMiddleware` throws an exception for a "method not allowed" error.

[1]: https://github.com/slimphp/Slim/blob/c4bdfa0bf05b6391f8bfe44852e289dba7cc40f4/tests/Middleware/RoutingMiddlewareTest.php#L72-L81

### PR DESCRIPTION
**Pull request by shadowhand**
Creates a new `RouteContext` class that can be used to gain access to the current request route, route parser, and routing results.

Fixes #2758 
Fixes #2761

### CODE REVIEW

**Comment by adriansuter** [comment]
Looks good, althoug I have to check in more depth.

Could you please add the slim file header comment to the two new files?

**Comment by shadowhand** [comment]
@adriansuter ✅

**Comment by adriansuter** [comment]
In `RouteContex::fromRequest()`, should we check if the three calls to 
`$serverRequest->getAttribute()` did not return `null`?

File: Slim/App.php [hunk 1]
```diff
@@ -68,11 +77,20 @@ public function __construct(
         );
 
         $this->routeResolver = $routeResolver ?? new RouteResolver($this->routeCollector);
-        $routeRunner = new RouteRunner($this->routeResolver);
+        $this->routeParser = $routeParser ?? new RouteParser($this->routeCollector);
```
Comment (l0gicgate) [inline Slim/App.php]: You can access the `RouteParser` via `$this->getRouteCollector()->getRouteParser()` no need to add it to the constructor or instantiate it here.

File: Slim/App.php [hunk 2]
```diff
@@ -68,11 +77,20 @@ public function __construct(
...
+        $routeRunner = new RouteRunner($this->routeResolver, $this->routeParser);
 
         $this->middlewareDispatcher = new MiddlewareDispatcher($routeRunner, $container);
     }
 
+    /**
+     * @return RouteParserInterface
+     */
+    public function getRouteParser(): RouteParserInterface
```
Comment (l0gicgate) [inline Slim/App.php]: Let's remove this getter as it is accessible via `$app->getRouteCollector()->getRouteParser()`

**Review by l0gicgate — CHANGES_REQUESTED** [review]

**Comment by shadowhand** [comment]
@adriansuter and do what? Throw an exception? PHP will already throw a `TypeError` if the values are `null` when trying to construct the `RouteContext`.

**Comment by l0gicgate** [comment]
@shadowhand we need to throw an exception to notify the user that routing hasn't been performed if those attributes are null. Probably throw a `RuntimeException`

**Comment by adriansuter** [comment]
Or an `InvalidArgumentException` as actually the given argument does not have sufficient information.

But then, a call to this static method has to be wrapped into a try-catch block. Probably it is better to throw a `RuntimeException`.

**Comment by shadowhand** [comment]
@l0gicgate @adriansuter updated with your requested changes.

File: Slim/App.php [hunk 3]
```diff
@@ -18,8 +18,10 @@
 use Slim\Factory\ServerRequestCreatorFactory;
 use Slim\Interfaces\CallableResolverInterface;
 use Slim\Interfaces\RouteCollectorInterface;
+use Slim\Interfaces\RouteParserInterface;
```
Comment (adriansuter) [inline Slim/App.php]: This can be removed.

File: Slim/App.php [hunk 4]
```diff
@@ -18,8 +18,10 @@
...
 use Slim\Interfaces\RouteResolverInterface;
 use Slim\Routing\RouteCollectorProxy;
+use Slim\Routing\RouteParser;
```
Comment (adriansuter) [inline Slim/App.php]: This can be removed.

**Review by adriansuter — CHANGES_REQUESTED** [review]
Some imports can be removed.

File: Slim/Middleware/RoutingMiddleware.php [hunk 5]
```diff
@@ -76,6 +84,7 @@ public function performRouting(ServerRequestInterface $request): ServerRequestIn
                     ->prepare($routeArguments);
                 return $request
                     ->withAttribute('route', $route)
+                    ->withAttribute('routeParser', $this->routeParser)
```
Comment (l0gicgate) [inline Slim/Middleware/RoutingMiddleware.php]: I just noticed that we are only adding the `routingResults` and `routeParser` attributes when a route is found. They should be included in both the `MethodNotAllowed` and `Found` cases. In the `MethodNotAllowed` case there won't be a `route` attribute so we need to make that attribute nullable on the `RouteContext`

File: Slim/App.php (hunk 3 above)
Comment (shadowhand) [reply Slim/App.php]: Would be nice if phpcbf would pick that up. 😕

File: Slim/Middleware/RoutingMiddleware.php (hunk 5 above)
Comment (shadowhand) [reply Slim/Middleware/RoutingMiddleware.php]: #2761 mentioned this too. I updated this PR to fix it.

**Review by l0gicgate — APPROVED** [review]
Looks good to me @adriansuter can you review one last time before I merge please?

**Review by adriansuter — APPROVED** [review]

**Comment by adriansuter** [comment]
Thanks - everything is fine.

**Comment by adriansuter** [comment]
We should not forget to update the docs about this new feature.

**Comment by l0gicgate** [comment]
@adriansuter absolutely
