### PR TITLE
Write to the error log if displayErrorDetails is false

### LINKED ISSUE #1761: Write to error_log when displayErrorDetails is false
When `displayErrorDetails` is false (the default), the ErrorHandler doesn't display any information. It should write to the `error_log` in this situation so that people who do not know about the `displayErrorDetails` setting can see that that Slim knows what went wrong. 

Bonus points for writing a note about the `displayErrorDetails` setting into the error_log too.

### PR DESCRIPTION
**Pull request by akrabat**
When displayErrorDetails is false, then the developer doesn't get any information on the exception. Add this information to the error log so that they can find it.

Closes #1761

### CODE REVIEW

**Comment by akrabat** [comment]
ping @silentworks, @codeguy

File: Slim/Handlers/Error.php [hunk 1]
```diff
@@ -81,6 +83,66 @@ public function __invoke(ServerRequestInterface $request, ResponseInterface $res
...
+    /**
+     * Render exception as Text.
+     *
+     * @param Exception $exception
+     *
+     * @return string
+     */
+    protected function renderTextException(Exception $exception)
+    {
+        $html = sprintf('Type: %s' . PHP_EOL, get_class($exception));
```
Comment (campersau) [inline Slim/Handlers/Error.php]: Nit: Why is this variable named `$html` instead of `$text`? The docblock says`Render exception as Text.`

File: Slim/Handlers/Error.php [hunk 2]
```diff
@@ -81,6 +83,66 @@ public function __invoke(ServerRequestInterface $request, ResponseInterface $res
...
+        if (($file = $exception->getFile())) {
+            $html .= sprintf('File: %s' . PHP_EOL, $file);
+        }
+
+        if (($line = $exception->getLine())) {
+            $html .= sprintf('Line: %s' . PHP_EOL, $line);
+        }
+
+        if (($trace = $exception->getTraceAsString())) {
+            $html .= 'Trace: ';
```
Comment (campersau) [inline Slim/Handlers/Error.php]: NIT: Why not 

``` php
$html .= sprintf('Trace: %s', $trace);
```

as everywhere else?

**Comment by akrabat** [comment]
@campersau Updated. Thank you!

**Comment by geggleto** [comment]
@akrabat thoughts on just including monolog?

**Comment by akrabat** [comment]
Don't want to. It's not the only PSR-3 logging library

**Comment by silentworks** [comment]
Looks good to me.

**Comment by akrabat** [comment]
/me waits for @silentworks to merge it…
