### PR TITLE
Fix #2890

### LINKED ISSUE #2890: PHPDoc of Slim\Http\Request::getParams it's wrong
Hello, In my project we use [PHPStan](https://github.com/phpstan/phpstan) for the static analysis, and throw me an error from the method `getParams` from `\Slim\Http\Request` because say the method can return null or array.

But i reviewd the two returns of the method and in both only return an array, that are or `$onlyParams` or `$params`, is the PHPDoc `return`wrong?

### PR DESCRIPTION
**Pull request by t0mmy742**
Closes #2890

### CODE REVIEW

File: Slim/Http/Request.php [hunk 1]
```diff
@@ -1186,7 +1186,7 @@ public function getQueryParam($key, $default = null)
      *
      * @param array|null $only list the keys to retrieve.
      *
-     * @return array|null
+     * @return mixed[]
```
Comment (l0gicgate) [inline Slim/Http/Request.php:1189]: wouldn't it be an array of strings only? It can't be anything else since it's parsed from a string.

```php
string[]|null
```

Comment (jacekkarczmarczyk) [reply Slim/Http/Request.php:1189]: What `?foo[]=1&foo[]=2` will be parsed to?

Comment (l0gicgate) [reply Slim/Http/Request.php:1189]:
```php
string|string[]|null
```

I'm not sure what all the combinations are to be honest, I'd rather not use `mixed` if we can define all of them instead.

Comment (t0mmy742) [reply Slim/Http/Request.php:1189]: It can't return null. No param will return an empty array.
This array can contains string and/or arrays.

?foo[]=1&foo[]=2 will be parsed to [foo[1, 2]]

Comment (l0gicgate) [reply Slim/Http/Request.php:1189]: > It can’t return null

What if the key doesn’t exist?

Comment (t0mmy742) [reply Slim/Http/Request.php:1189]: `public function getParams(array $only = null)`

If `only` is not null, and values in `only` does not exist, `getParams()` return an empty array.

Comment (l0gicgate) [reply Slim/Http/Request.php:1189]: My bad @t0mmy742 the diff's header had me confused for a second. This is correct.

**Review by l0gicgate — APPROVED** [review]
